### PR TITLE
Build puppet and bolt using system openssl

### PR DESCRIPTION
**Pull request by trevor-vaughan**

### CODE REVIEW

**Comment by judyj** [comment]
@trevor-vaughan @op-ct - 
I know this isn't in the current PR, but in the README.md, there is an incomplete thought:

- List and/or set which PR checks are required on each repo (github_inventory::required_checks)
- Report which _---??????  what is being reported?_

**Comment by trevor-vaughan** [comment]
@judyj No idea, I didn't write that

**Comment by op-ct** [comment]
> @trevor-vaughan @op-ct -
> I know this isn't in the current PR, but in the README.md, there is an incomplete thought:
> 
> * List and/or set which PR checks are required on each repo (github_inventory::required_checks)
> * Report which _---??????  what is being reported?_

@judyj  Looks like that could have been:

> * Report repos with GitHub Actions workflows (`github_inventory::workflows`)

I'll patch it in a separate push

**Comment by judyj** [comment]
@op-ct ok. i will create a quick ticket so it can be a different patch

**Comment by op-ct** [comment]
The code looks reasonable to me, with the big caveat that I've never used Vanagon.

I haven't been able to build either Dockerfile from a SIMP 6.5.0/EL7 host using docker or buildah—after various tweaks to hidepid, ulimits, uid mappings, and graphroot locations, EL7 and EL8 builds still fail at different points with errors about not being able to `utime`.

None of this will stop the patch from merging; this project's goal was to provide a place to share individual releng tools even if they aren't robust enough to be productized (the README even says, "Don't let polishing things hold you up from contributing").  However, it would be good to have a minimal README with some prereqs and basic instructions if anyone other than @trevor-vaughan is expected to use them in the future.

**Review by op-ct — APPROVED** [review]
(lgtm, but unverified—see comments above)

**Pull request merged**
